# yaml-language-server: $schema=https://raw.githubusercontent.com/evilmartians/lefthook/refs/heads/master/schema.json
output: [summary]
templates:
  run: run --quiet --no-progress
no_auto_install: true
pre-commit:
  jobs:
    - name: clang-format
      glob: "*.{cpp,hpp,h,mm}"
      run: pixi {run} clang-format -i {staged_files}
